### ISSUE TITLE
(real) Arguments?

### ISSUE THREAD

**Issue by jtmarmon** [tj/robo#12]
It'd be great to be able to supply values for variables as arguments 
```yml
speak:
  summary: Tell me something
  exec: echo {{word}}
```

```
$ robo speak word:hello
hello
```

Are you averse to this for any reason? I know you were going for simplistic, but it seems like quite a lot of power for minimal complication, especially if you somehow piggyback it off the existing variable system
