### ISSUE TITLE
using on windows, mac and linux

### ISSUE THREAD

**Issue by tutume** [tj/robo#17]
Hi,

I'm trying to find some way to use command line for some tasks that will work the same way on windows, mac and linux to help some users and even new technician to work on command line. The idea is to provide a simpler tutorial that will work on both platforms.

Example: To install a program that exists on both OSs, each of provide a different set of commands to do that. Using robo, maybe will be a good solution. Lets say you want to install atom.
- on windows: choco install atom
- on mac: brew install atom
- on linux: sudo apt install atom
- with robo: robo install atom

I would create a global robo.yml for each platform (better yet change robo code to identify the OS and allow to provide different commands for each OS)

But by new, I'm trying to use it as is and I'm facing with some issues:
1. command: don't work well with params
2. exec: don't work, return not support by windows

Would you (or someone) be willing to work on this changes/fixes? I would do it myself, but I'm not actually a developer and didn't know how to make this changes here. I didn't try other solutions as most of then are on python or ruby and it would need a runtime enviroument. What I liked in robo is that it is in go and it is a single binary.

Thanks and if I can help in anything to acomplish this changes, please, let me know.

******* simple ideia of a robo.yml file to allow multi-OS commands ******
```
#when the command is the same for all platforms
echo:
   summary: show a text
   exec: echo
   usage: "[text]" 
```` 
```
#when the command is different
install:
   summary: install some program
   exec-linux: sudo apt install
   exec-mac brew apt install
   exec-windows: choco install
   usage: "[program]"

show-file:
   summary: show file content
   exec: cat
   exec-windows: type
   usage: "[file]"
```

**** how I'm using and what don't work ****
```
echo:
  summary: display a text
  command: echo
  usage: "[text]"
on both it don't show anything, sounds like it doesn't receive the parameter

echo:
  summary: display a text
  exec: type 
  usage: "[text]"
```

on windows it returns: error: not support by windows
