### ISSUE TITLE
How to nest variables

### ISSUE THREAD

**Issue by yujunz** [tj/robo#43]
Trying to nest variable in another variable but seems not working. How should I handle such case in robo?

```yaml
deploy:
  summary: deploy longhorn system
  exec: kapp deploy {{.kapp.flags}}

delete:
  summary: delete longhorn system
  exec: kapp delete {{.kapp.flags}}

port-forward:
  summary: port-forward service to localhost
  exec:	kubectl port-forward -n longhorn-system svc/longhorn-frontend 8080:80

variables:
  kapp:
    namespace: kapp
    app: longhorn-system
    flags: --namespace {{.kapp.namespace}} --app {{.kapp.app}} --diff-changes
```

```sh
❯ robo variables

    kapp.app: longhorn-system
    kapp.flags: --namespace {{.kapp.namespace}} --app {{.kapp.app}} --diff-changes
    kapp.namespace: kapp
```
