### ISSUE TITLE
Bare task names list for completion

### ISSUE THREAD

**Issue by rafi** [tj/robo#46]
It would be nice to have a way to list task names without colors and formatting so it could be consumed by a bash/zsh/fish completion script for the task name. Something like `robo -q` ?

Adding this to `robo.yml`:
```yaml
templates:
  list: |-
    {{range .Tasks}}{{.Name}}{{ print "\n" }}{{end}}
```

And sourcing this bash completion:
```sh
#/usr/bin/env bash
_robo_completion() {
  if [ "${#COMP_WORDS[@]}" != "2" ]; then
    return
  fi
  COMPREPLY=($(compgen -W "$(robo)" -- "${COMP_WORDS[1]}"))
}

complete -F _robo_completion robo
```

Works nicely. But it's annoying adding the list template in each `robo.yml` file.
