### ISSUE TITLE
Feature Request - Optionally Print the command before running a task and maybe some 

### ISSUE THREAD

**Issue by vikas027** [tj/robo#50]
I think it will be a good idea to optionally print the command before running a task to make the output a bit easier to read. I am proposing to make this optional and the command in some case could contain secrets too.

Also, it would be great if we can some line breaks or something more readable between tasks. As of now, reading logs is a bit difficult as there is no distinction in the logs.

Alternate solution:
use an echo statement in the command itself
```yaml
hello:
  summary: some task
  command: |
    echo which terraform
    which terraform
```

**Comment by yields** [comment]
Perhaps we should add a `-v | --verbose` flag, would that work for you?

**Comment by vikas027** [comment]
Hey @yields ,

That does not help much. I don't see the command being run

```yaml
---
hello1:
  summary: some task1
  command: |
    echo which {{ .iac }}
    which {{ .iac }}
  examples: # robo help tf-plan-mod
    - description: Find path of {{ .iac }}
      command: which {{ .iac }}

hello2:
  summary: some task2
  command: |
    robo -c {{ .robo.file }} hello1
    echo which {{ .iac }}
    which {{ .iac }}
```

This is the output
```bash
❯ robo hello2 --verbose
which terraform
/usr/local/bin/terraform
which terraform
/usr/local/bin/terraform
```
