### ISSUE TITLE
Feature Request - Interpolate variables in examples too

### ISSUE THREAD

**Issue by vikas027** [tj/robo#51]
It would be good to have interpolation of variables in `examples` too

```yaml
variables:
  iac: terraform

hello:
  summary: some task
  command: |
    echo which {{ .iac }}
    which {{ .iac }}
  examples: # robo help tf-plan-mod
    - description: Find path of {{ .iac }}
      command: which {{ .iac }}
```

This results in this
```bash
✦ ❯ robo help hello

  Usage:

    hello 

  Description:

    some task

  Examples:
  
    Find path of {{ .iac }}
    $ which {{ .iac }}
```

I would like is
```bash
✦ ❯ robo help hello

  Usage:

    hello 

  Description:

    some task

  Examples:
  
    Find path of terraform
    $ which terraform
```
