### ISSUE TITLE
Cannot expand variable in other variable on the top of line

### ISSUE THREAD

**Issue by mitsuru793** [tj/robo#52]
This yaml file not works.

>  error loading configuration: yaml: line 10: did not find expected key

I got the above error.

```yaml
run:
  exec: echo {{.script}}

variables:
  root: $(echo $HOME/myproject/)
  script:  {{.root}}/index.php
```

However this is works.

```yaml
run:
  exec: echo {{.script}}

variables:
  root: $(echo $HOME/myproject/)
  script:  index.php/{{.root}}
```

I'm restricted where expanding variable only after string.
