### ISSUE TITLE
Calling dependent tasks

### ISSUE THREAD

**Issue by sporto** [tj/robo#8]
Is this the idiomatic way of calling dependent tasks?

robo.yml:

```
one:
  command: echo one

two:
  command: echo two

all:
  command: |
    robo one
    robo two
```

So, calling robo again with the sub task

Nothing like make where you declare the dependency directly?

makefile:

```
one:
    echo one

two:
    echo two

all: one two
```

Just checking if I am doing it right, thanks.

**Comment by tj** [comment]
nope, nothing built in yet. I didn't intend on emulating everything a Makefile can do, we don't have any use-cases with dependencies yet but I could see even some basic hooks being helpful, something like:

```yml
docker.build:
  command: ...
  after:
    - docker.push
```
